### ISSUE TITLE
int8精度基本为0？

### ISSUE THREAD

**Issue by HuKai97** [Melody-Zhou/tensorRT_Pro-YOLOv8#29]
按照您的步骤，测试了yolov5和yolov8的fp32、fp16的精度都算正常，都降了一点，但是int8的精度非常低，这可能是什么原因呢？
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.016
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.097
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.016
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.019
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.019
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.017
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.114
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

**Comment by Melody-Zhou** [comment]
@HuKai97 从两方面考虑吧，一个是校准数据集另一个是校准算法，不过从你的精度来看大概率是校准数据集选择问题，按理来说 PTQ 量化精度不可能下降这么多，是不是你的校准数据没有包含所有类别，不能很好的表示整个数据集呢？
